# Generated by Django 4.1.1 on 2022-10-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="subcategories",
            field=models.ManyToManyField(blank=True, to="tracker.category"),
        ),
    ]
